### ISSUE TITLE
Failing to install IPAs 

### ISSUE THREAD

**Issue by braystumble** [LinusHenze/Fugu14#102]
Hi. Looked through trying to find a solution to this and I tried the ones that were up and they didn't work for me. I feel like the fix is extremely simple but i cant pin point what to do. Can anyone help with this. 

I'm sorry for any inconvenience and thank you.

(I'm referring to: " cp: ../arm/iOS/Fugu14App/build/Build/Products/Release-iphoneos/Fugu14App.app: No such file or directory
Failed to create IPAs! Exit status: 1 " at the bottom of the screenshot.)

![Screen Shot 2021-10-27 at 8 01 26 PM](https://user-images.githubusercontent.com/93295388/139164117-41ed2323-3376-42e4-a0b4-a7764a4ae1d3.png)

**Comment by AlexanderGates-iOS** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/93331932/139288545-f6d6d4ce-1727-4020-b22a-dcf4ad16c02d.jpeg)
> 
> I'm having this issue... Any pointers would be GREATLY appreciated!

I'm also having this issue
