### ISSUE TITLE
Failed to install untether.

### ISSUE THREAD

**Issue by PoopickerDowsion** [LinusHenze/Fugu14#130]
Device: iPhone 12 ProMax
OS Version:14.5.1
Description:
I submitted [Issue#51](https://github.com/LinusHenze/Fugu14/issues/51) 

This situation stuck for few days.
After uncover updates, I tried uncover 7.0.1.

Finally I got this result.

![failed](https://user-images.githubusercontent.com/91650603/139406124-fce8ec71-99f4-4101-8419-b599a39f6a51.jpg)

I've restored rootfs before updating uncover to 7.0.1 via altstore.

**Comment by plia7** [comment]
@PoopickerDowsion Hi there, how did you "Forced restore"? I have the same issue as you:
https://github.com/LinusHenze/Fugu14/issues/253
