### ISSUE TITLE
“Failed to find a contiguous region!” Fugu14 after patch (iPad Air 4th Gen // iOS 14.4)

### ISSUE THREAD

**Issue by realrodri** [LinusHenze/Fugu14#137]
Seems like I'm not the only one having this issue. People on Reddit is having this exact error with this exact device on this exact iPadOS version.

The iPad Air 4th Gen has the same processor as the iPhone 12 Pro Max (A14 Bionic), and if it works on iPhone 12/Pro/Max, it *technically* should work on this iPad too.

Well, no. Not exactly. Attaching a picture below so you can see what's really happening:

![image](https://user-images.githubusercontent.com/40494400/139443737-76885af7-a6b6-4d7c-be36-86d0eb334829.jpeg)
![image](https://user-images.githubusercontent.com/40494400/139443375-5dd92da9-27cd-4830-9ec7-46ceaea18188.jpeg)

**Comment by mtabanja** [comment]
any update on this issue?

**Comment by realrodri** [comment]
> any update on this issue?

I jailbroke using the old method (compiling it) and it worked!

**Comment by mtabanja** [comment]
> > any update on this issue?
> 
> I jailbroke using the old method (compiling it) and it worked!

can you help me out by giving me a guide link for the method you used?is it the xcode one?

**Comment by realrodri** [comment]
> > > any update on this issue?
> 
> > 
> 
> > I jailbroke using the old method (compiling it) and it worked!
> 
> 
> 
> can you help me out by giving me a guide link for the method you used?is it the xcode one?

Yep, it's the Xcode method. There are plenty of YouTube tutorials out there, but tbh I just followed ProfeJuAntonio's tutorials (it's in Spanish), but if you want to get it in English, you can browse it on YouTube and you'll find it first.

**Comment by mahoma1991** [comment]
> > > > any update on this issue?
> > 
> > > 
> > 
> > > I jailbroke using the old method (compiling it) and it worked!
> > 
> > 
> > 
> > can you help me out by giving me a guide link for the method you used?is it the xcode one?
> 
> Yep, it's the Xcode method. There are plenty of YouTube tutorials out there, but tbh I just followed ProfeJuAntonio's tutorials (it's in Spanish), but if you want to get it in English, you can browse it on YouTube and you'll find it first.

Give me Plesse the spanish Link of this YouTube video!

**Comment by TechaN9na** [comment]
I'm also having this issue on Ipad Air 4 14.4 will a new version, please advise.

**Comment by LinusHenze** [comment]
Latest build fixes this issue
