### ISSUE TITLE
“Attempting to write a readonly database” // Fugu14 compile error

### ISSUE THREAD

**Issue by realrodri** [LinusHenze/Fugu14#153]
I'm fucking tired. Seriously. I've created another Apple ID to see if this solves the error 65 I was having and yes it did, but I'm facing ANOTHER error.

Exit code: 1
"Attempting to write a readonly database".

I have my iPad connected to the Mac, I have updated Xcode, I've changed the Bundle Identifier, I've changed the developer account, I installed brew and all the dependencies Fugu14 needs, I gave Xcode all privileges to compile it using Python, I installed latest version of Python.

Everything you can imagine I've could done, I did.

I'm absolutely mad at this point, and most probably I'm writing this with my head looking like a volcano erupting, because I spent more than 4 hours trying to figure out what the fuck is happening and what I'm doing wrong.

Apple revoked 2 of my main Apple IDs for 7 days and I can't create more App IDs, so you can imagine the level of madness I'm right now.

Any help is appreciated.

**Comment by jaygee562** [comment]
what's your issue? and why are you compiling fugu14 through Xcode? that's the old way of doing it now.

**Comment by realrodri** [comment]
No issue now. Jailbreaking with Altstore is broken in some devices as stated by Linus. Already jailbroke with source code Fugu14 and flawlessly good. This jailbreak is insane.

**Comment by badger200** [comment]
@realrodri This jailbreak sucks because anything that uses the Neural Engine will eventually trigger a kernel panic (basically every game with ads). Prove it: launch Fruit Ninja 2. It will panic before you can even reach the first level of the gameplay. We are tracking this issue on the pwn2ownd Undecimus GitHub.
