### ISSUE TITLE
14.8 jailbreak

### ISSUE THREAD

**Issue by keko01** [LinusHenze/Fugu14#155]
Do you have a jailbreak for version 14.8?

**Comment by fikaa73** [comment]
Please close this and **READ MANUAL BEFORE POSTING HERE**

**Comment by Shulkk** [comment]
the README clearly states that it's for 14.3-14.5.1, and with modification it can be 14.0-14.5.1

**Comment by Cryptiiiic** [comment]
@keko01 please close this issue, 14.8 is not happening that is not the purpose of fugu14.

**Comment by keko01** [comment]
The issue is closed for me.
