### ISSUE TITLE
help me, FAILED TO INSTALL UNTETHER

### ISSUE THREAD

**Issue by XGsGorila** [LinusHenze/Fugu14#166]
When I press the update button untethered I get this error and my uncover says not supported, is there a solution?
![2021_11_01_04_14_IMG_0049](https://user-images.githubusercontent.com/13209079/139659032-f7c0d4b4-e0fb-444f-a830-0b3986361fc7.PNG)
![2021_11_01_04_12_IMG_0048](https://user-images.githubusercontent.com/13209079/139659057-c33fa2a8-0568-4bce-877e-9342aa98157f.PNG)
![139490640-da43ffd3-e87c-4025-adf0-a6b2ed37f087](https://user-images.githubusercontent.com/13209079/139659631-bbf5874d-f9e8-45a0-b2bb-1ea8d0018e8e.png)

**Comment by PoopickerDowsion** [comment]
Use iRecovery, 
irecovery -s
boot-args untether
saveenv
reboot

Do it and try

**Comment by fikaa73** [comment]
Put your boot-args to x, restore rootfs and do everything from altstore

**Comment by XGsGorila** [comment]
#
