### ISSUE TITLE
Black Screen on Fugu14

### ISSUE THREAD

**Issue by PoetG** [LinusHenze/Fugu14#179]
I get stuck on this black screen after I’m redirected the second time from AltStore 
https://user-images.githubusercontent.com/93642145/140023559-d63ef48e-1bc6-451d-8b52-80dc8fee7bc4.MP4

**Comment by adibarra** [comment]
Same issue here on a XR running 14.4

**Comment by PATTSystem** [comment]
Issue 11 is the same thing

**Comment by PATTSystem** [comment]
and there is no fix yet

**Comment by PoetG** [comment]
My bad didn’t I missed that some how but hopefully it gets fixed soon

**Comment by PoetG** [comment]
> 
> 
> and there is no fix yet



> 
> 
> Same issue here on a XR running 14.4

I just restarted my IPhone (stupid I know) and it started working lol not sure what caused the problem tho...
