### ISSUE TITLE
Untether.app not appearing (SE2 14.3)

### ISSUE THREAD

**Issue by thekio1984** [LinusHenze/Fugu14#184]
14.3, SE2, ive roots numerous times, installed, reinstalled fugu & unc0ver, ive updated untether, everything & the app still doesnt show...i followed same process as i did when initially installed fugu, updating fugu after sleep bug & when 7.0.2 dropped (i didnt realise could update u0 without reinstalling fugu completely lol), ive even updated untether via fugu...(install fugu via mac, sideload unc0ver ipa)

everything installs without any errors & does what it should do....but still untether.app isnt showing...

any ideas??

![5F3A7DAC-73B4-471B-8826-CEE86A35C658](https://user-images.githubusercontent.com/31554776/140219175-432991d6-e4d6-4c13-8613-99a56419901c.png)

**Comment by iM4CH3T3** [comment]
Yes same on my iPad Air4 14.3
Even after restoring rootfs and restore all settings and content in settings …

**Comment by thekio1984** [comment]
> Yes same on my iPad Air4 14.3
> Even after restoring rootfs and restore all settings and content in settings …

Strange thing tho..everything shiws as untether.app being installed...setup & installs fine, no errors...even appears in apps in filza: 
![F64AFA22-8778-4C0D-90F4-A12AD282403C](https://user-images.githubusercontent.com/31554776/140235064-1a612849-d185-4ac2-b557-7e62e0f9f641.png)

it just doesnt want to appear on my HS 🤷🏼‍♂️🤷🏼‍♂️

**Comment by thekio1984** [comment]
> > Yes same on my iPad Air4 14.3
> > Even after restoring rootfs and restore all settings and content in settings …
> 
> Strange thing tho..everything shiws as untether.app being installed...setup & installs fine, no errors...even appears in apps in filza: ![F64AFA22-8778-4C0D-90F4-A12AD282403C](https://user-images.githubusercontent.com/31554776/140235064-1a612849-d185-4ac2-b557-7e62e0f9f641.png)
> 
> it just doesnt want to appear on my HS 🤷🏼‍♂️🤷🏼‍♂️

Even unc0vers jailbreak log shows it as installed and runs ui cache 

![25D8B152-BD67-42B6-BCCE-D26A3CA694FD](https://user-images.githubusercontent.com/31554776/140235762-38ba33a3-2c05-4e55-ae5b-df2c1a422134.jpeg)

**Comment by thekio1984** [comment]
Even shows in choicy's application list along with unc0ver...![7873AB5B-F763-4083-B9F4-06205B8BC139](https://user-images.githubusercontent.com/31554776/140240690-2ecbd573-21e9-458a-91d2-8d3fd398b9d7.png)

Wth 🤦🏻‍♂️

**Comment by iM4CH3T3** [comment]
Tried to Install terminal and run uicache?

**Comment by thekio1984** [comment]
> Tried to Install terminal and run uicache?

Yep, tried everything, everything shows app being there, even if i delete normal u0, untether.app data remains..its just not showing on homescreen, which makes it totally inaccessible lol...im not silly or stupid, i know how to install this jailbreak, the apps there, but it aint.

id try reinstalling, but i dont see doing it for the 9-10th time is going to make any difference, i shoulda just left it.....nothing in the latest update benefitted me anyways, in fact seems to have cause more issues than fixed 😱

**Comment by iM4CH3T3** [comment]
![image](https://user-images.githubusercontent.com/12032829/140243708-900a1530-4ef1-4ce6-9114-a1c27b4519dc.jpeg)




Installed with Xcode but no untether app , also not in applications folder... 
AltStore not prompting anything...
Actually a working fugu not recognized by unc0ver and AltStore...

**Comment by thekio1984** [comment]
> ![image](https://user-images.githubusercontent.com/12032829/140243708-900a1530-4ef1-4ce6-9114-a1c27b4519dc.jpeg)
> 
> Installed with Xcode but no untether app , also not in applications folder... AltStore not prompting anything... Actually a working fugu not recognized by unc0ver and AltStore...

Yep basically same..fugu appears to work, but has zero interactions with unc0ver...odd thing is, before i saw the latest updates to fugu tweeted by pwn & installed...EVERYTHING was fine, untethered 7.0.2, now even 7.0 & .0.1 dont work.....seems whatever codes been added/changed in latest commits, seems to have broken 14.3 in some way

**Comment by thekio1984** [comment]
Closing issue, after all this, I uninstalled simplehome (too enable app library), low & behold....i found the untether app.

If in my boat theres 2 u0 app icons in app library, only one will let you drag & stay on HS, thatll be untether.app, as unc0ver.apps already there & it wont dupe an app on HS 👌🤘🤘

**Comment by thekio1984** [comment]
@iM4CH3T3 Try looking in app library, was there for me, when fugu deleted, it didnt delete, it just removed from HS, so when reinstalled, settings remained same, still 'removed' from HS 🤞
