### ISSUE TITLE
Setup failed - Fugu14App.closure doesn't exist

### ISSUE THREAD

**Issue by ByQuartz** [LinusHenze/Fugu14#219]
So i get the error "The File Fugu14App.closure doesn't exist.

Here is a Screenshot of that.
Any idea How to fix that?
I have an Iphone 11 with IOS 14.3
AltStore 1.4.8
and tried to install Unc0ver 8.0.0

![71a63609-246c-44e3-9fa6-279240a17db6](https://user-images.githubusercontent.com/67395618/147712529-df2c24e1-b048-4d79-8312-afab6bb5ec52.jpg)
"

**Comment by UInt2048** [comment]
Try 8.0.1

Also, Fugu14 != unc0ver

**Comment by ByQuartz** [comment]
Still the same problem

**Comment by Smurf1987** [comment]
![Uploading 3815C8F9-DE9A-4183-A2C4-D6A63E0B8BAE.png…]()

**Comment by Matteo02p** [comment]
Same to me

**Comment by ByQuartz** [comment]
I managed to fix the issue by just deleting my previous Unc0ver Jailbreak.
After i deleted the unc0ver app i restarted my Phone so its not Jailbroken anymore and the tried to install Unc0ver x Fugu14 again and that worked. I hope i can help somebody with that.
Also i used Unc0ver 8.0.2
