### ISSUE TITLE
Kernel Panic

### ISSUE THREAD

**Issue by cargo11900** [LinusHenze/Fugu14#220]
I’m experiencing consistent kernel panics on unc0ver’s 8.0.0 Fugu untether. I’m on iOS 14.3 iPhone 11, I installed Tiktok and it had caused consistent KPs several times a day. Uninstalling the app has obviously solved the issue. I know this may not be a result of fugu itself but I thought I’d bring it to your attention as well.

**Comment by cargo11900** [comment]
This appears to an unc0ver specific issue and doesn’t appear to be related to fugu, partly coincidence.

**Comment by joshuah345** [comment]
this doesn’t occur for people using unc0ver alone (14.8 here)
