### ISSUE TITLE
Stuck on "Threads created" - iPhone XR 14.5.0 - Missing Offsets

### ISSUE THREAD

**Issue by VivaLaRobo** [LinusHenze/Fugu14#37]
I've done all the steps correctly, but it gets stuck on "Threads created" after running the Fugu14 app. Any ideas?

**Comment by mailinglists35** [comment]
@pwn20wndstuff & @rileytestut, would you please update your bits with this fix?
Affected by this issue, iPadOS 14.5.1 iPad11,3
Thank you
