### ISSUE TITLE
Restored to orig-fs using SnapBack, fugu now says that it's already installed.

### ISSUE THREAD

**Issue by JaxonKEKW** [LinusHenze/Fugu14#90]
iPhone 11
iOS 14.5.1

I restored my rootfs using SnapBack since the fugu app got deleted. I was having some issues so I needed to restore the rootfs. Upon re-installing Fugu after this, I get "Fugu is already installed" after I click Jailbreak + untether, and unc0ver now says Unsupported again, so I'm basically stuck.

**Comment by i91h1r** [comment]
> If so why not use uncover to restorefs and what happens when you tap on install. ￼
uncover Display not supported ，so no restore rootfs choose

**Comment by RiskyAppleJuice** [comment]
Yo dawg

**Comment by RiskyAppleJuice** [comment]
Yo look at ![image](https://user-images.githubusercontent.com/50676556/139519599-5a45787b-d666-49d7-8078-45fe8526a9d9.png)

**Comment by RiskyAppleJuice** [comment]
#142

**Comment by RiskyAppleJuice** [comment]
![image](https://user-images.githubusercontent.com/50676556/139519615-79a4d432-e6e1-44f0-bf9d-5b237ac98f8c.png)

**Comment by RiskyAppleJuice** [comment]
They have the solution for you but you gotta hell shit. I don't know if you are experience or not. Read carefully and double check your work. 
If you fuck up. 
Worst case scenario. Gotta update to latest. 
Best case you will get Cydia back ￼
